### ISSUE TITLE
Certain fights not finishing

### ISSUE THREAD

**Issue by renimg** [Truthkey/KH2FMRandomizer#1]
posted this on the wrong thing, oops.

for some reason a lot of fights (yen sids first tower fights, bailey, etc) don't finish after killing all the enemies

**Comment by Truthkey** [comment]
Yeah, it's a known issue. The game expects a given event to have certain amount of enemies defeated but some of the enemies from the list don't add to that count, so the battle doesn't end. I'll fix it at some point in summer.
