### ISSUE TITLE
if you get a weapon during parts of the prologue and equip it gets removed at points where roxas switches weapons

### ISSUE THREAD

**Issue by duduhed** [Truthkey/KH2FMRandomizer#13]
doubt you can do much here but disable weapon spawns in the prologue

**Comment by Truthkey** [comment]
Does it cause any problem during the game? I believe I can add an option to filter weapons.

**Comment by duduhed** [comment]
it's fine mostly just a result of the game replacing roxas' weapon in the tutorial after cutscenes and deleting the struggle club in the last segment
