### ISSUE TITLE
Excluding enemy randomization doesn't seem to be working

### ISSUE THREAD

**Issue by Enerzma** [Truthkey/KH2FMRandomizer#15]
I do not have enemy randomization checked off on the GUI, yet when I get into the game, I have enemies showing up in places they should not. Am I using the GUI wrong or is this an error in the program?

**Comment by Truthkey** [comment]
If the checkmark doesn't show in the enemy randomization button, it shouldn't randomize any enemy at all.

**Comment by Enerzma** [comment]
I thought maybe I'd messed with something I shouldn't, so I deleted the randomizer and re-downloaded it.... Now it's not randomizing at all..

**Comment by Enerzma** [comment]
I'm uhhh, kinda dumb. Turns out the problem when I redownloaded it was simply that I didn't realize toggling enemy randomization did enemies AND bosses. Still don't know what the problem was the first time though.
