### ISSUE TITLE
VCRUNTIME140_1.dll was not found

### ISSUE THREAD

**Issue by Anon3456** [Truthkey/KH2FMRandomizer#16]
Hello im trying to use your randomizer but this problem persists and ive tried manually downloading it getting the programs but nothing one of your older builds works but it has less for the GUI please respond soon 
![image](https://user-images.githubusercontent.com/64225571/80140931-adfe9800-8576-11ea-9101-1f8562c2dcf3.png)

**Comment by Anon3456** [comment]
If possible a link to a working iso would be appreciated all the ones i got were modded or ones that just dont work

**Comment by Truthkey** [comment]
That means you don't have the VC++ Redistributables. Install them and it should work.
