### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by TrueEftekas** [Truthkey/KH2FMRandomizer#17]
Hi, first off, I'd like to say thanks for your incredible work.  Before I start I'll just say that I have recommended settings on. Onto my issues:
1- Upon loading into a new area (it was the disney castle courtyard) the game kept loading for a long time until the emulator gave me an error (sorry I didn't save it, but there was an option to either close the game or ignore it)
2- One of the forced fights had an enemy (I believe it's a minute bomb) that did not spawn correctly, and so the fight could not be continued. The fight was the second one in Yen Sid's tower. Enemy seed 7C94EF28.
3- I have seen some odd abilities, one was Magic Haste, which is a drive exclusive ability and can't be toggled, and another was called "Slow 2" in xeeynamo's patch, it had "Delete" as a description.
Thanks, I hope to see this project succeed.
EDIT: During the randomization process, I see KH2 320/5159 Index was out of bounds, Is there something wrong with my rom or is this normal? (nevermind, this was fixed by using a clean rom instead of the english one, so I should randomize first then english patch, not the other way around)
EDIT2: Upon re-randomizing with the same seed with minute bombs blacklisted, the enemy was randomized to an Air Viking, but still didn't show up, the enemy in that slot refuses to load.
EDIT3: Multiple randomizations later, the enemy in that slot refuses to appear regardless of what it is.
EDIT4: I finally fixed the non spawing enemy issue by deleting the randomizer folder and re-extracting it, I guess using the english patch caused some bad exports that lead to problems later.
EDIT5: Aaaand now I'm having a consistent crash right before dealing the final blow of the Station of Awakening dusk fight.

**Comment by Truthkey** [comment]
Yes, this is a known crash and has been fixed in the last update!
