### ISSUE TITLE
Patching Order

### ISSUE THREAD

**Issue by sgern** [Truthkey/KH2FMRandomizer#20]
What patches are compatible with this randomizer, and in what order should I apply them? I'm looking at the following patches:

- Crazycatz00 Translation + Dual Audio + Dual Audio Videos + Extras
- TopazHacker 2DWideFix
- SusmitDas HDification
- VladVidya HDification (does this replace and supercede the other one?)

**Comment by Truthkey** [comment]
Technically translation patches or HD mods shouldn't affect how the randomizer works.
