### ISSUE TITLE
Station of Serenity Crash, Other Issues

### ISSUE THREAD

**Issue by sgern** [Truthkey/KH2FMRandomizer#21]
I tried the randomizer, but it crashed as soon as I finished the 3 Dusks (well, a Samurai, a Large Body, and a Timeless River Large Body) fight in the prologue (right after choosing the Dream weapons). I had Bonus Rewards randomized, and looking at the spoiler logs, that fight, which normally gives Aerial Recovery, instead tried to give 3 MP, an Armor Slot, Drive Converter, and Negative Combo. Would it be possible for you to blacklist certain rewards that crash the game, at least for Roxas?

Also, I looked through the other spoiler logs, and Sora gets some strange abilities when leveling up, such as Drive Form combo abilities, other party members' Limits, and something called "Slow 3". Whether or not these crash the game when obtained or equipped, these abilities probably wouldn't work for Sora, and they might be missing from their proper owners. Could you make sure that any ability randomization doesn't mess with these expected, innate abilities?

**Comment by Truthkey** [comment]
Yes, I've already looked into this and should be fixed!
