### ISSUE TITLE
The option to not randomize Roxas's prologue doesn't work

### ISSUE THREAD

**Issue by kokorikopi** [Truthkey/KH2FMRandomizer#4]
No matter how many times I click, no matter how many variables I try and mess with, I can't make Roxas's prologue not randomized. This basically renders every run potentially unwinnable without a number of exceptions that make the main part of the game less interesting, such as Lexaeus being unbeatable at Struggle, or Storm Rider not working in small arenas.

**Comment by EngiPUBLIC** [comment]
I have no advice for you, but im looking how to actually make this work because i have no fucking idea and it does not create the kh2fm.new.iso or whatever it is.

**Comment by zeebo30** [comment]
Also having this issue. Also learned that apparently if the dusks get replaced with heartless the struggle bat can kill them and you can softlock so that's cool. fix please!

**Comment by Truthkey** [comment]
The Roxas prologue non randomization button was never meant to work, it was my mistake on my end by making it seem like it was available. That's something I fixed.

I will continue to work on this project until it works properly in most situations.
