### ISSUE TITLE
Issue Making KH2FM.NEW.ISO

### ISSUE THREAD

**Issue by EngiPUBLIC** [Truthkey/KH2FMRandomizer#5]
Mainly when it's copying files to ARD folder, it doesn't really make any file in one sort of 'nother.
I have the .iso in, renamed, and by the .exe; the ard folder has not been modified. Along with all of that I have tried the Japan version along with the english patch; it all stopped before the out of [5700's] with a completed code of (0) offhand java scripting tells me it's a success code and after that the exe closes and I gottten angry for doing this and other methods for the last 4 hours. I got nothing. Am i missing something?? or is the instructions not enough, I need something else?

**Comment by zeebo30** [comment]
Well this isn't a java program so your java scripting knowledge won't help with this. I haven't had the issue you're having, only issue i've had is that certain options in the configGUI don't work (namely exclude roxas prologue)

**Comment by zeebo30** [comment]
However, this hasn't been updated since January of 2019 so chances are this is an abandoned project

**Comment by Scalex-Orxzion** [comment]
I had this problem too however i seem to have found the solution. it seems the exe only works with the original ISO being "Kingdom Hearts II - Final Mix+ (Japan).iso" and nothing else it has to be "Final Mix+" not just Final Mix.  you can get this iso version from a few places but i found mine from here.

https://coolrom.com.au/roms/ps2/45499/Kingdom_Hearts_II_-_Final_Mix+_(Japan).php

Hope this helps you!

**Comment by Truthkey** [comment]
The program should work with any KH2 version, even the USA/EUR/JP versions as Govanify's tool can extract them all.
