### ISSUE TITLE
Nothing getting randomized

### ISSUE THREAD

**Issue by Kysakio** [Truthkey/KH2FMRandomizer#6]
I'm using an ISO with an English patch (https://cdromance.com/ps2-iso/kingdom-hearts-ii-final-mix/) but nothing is getting randomized. I used the GUI and got some spoiler logs one of which is the LevelUp log but I'm just getting the vanilla abilities as I level up. (I chose the shield and got item boost at level 7 even though it says that I should be getting Crime and Punishment.)

**Comment by Kysakio** [comment]
The problem was on my end. I tried moving the randomized game which didn't work. I then tried putting things back but I guess I did it wrong. When I re-downloaded the randomizer and tried again, everything started working great.
Thanks for all the hard work you've put into this.

**Comment by RenFinkle** [comment]
For anybody that's looking at this issue too, sometimes you have to generate multiple times to get results, did it twice and it's working for me now!
