### ISSUE TITLE
Bosses Roxas can't beat At Positions

### ISSUE THREAD

**Issue by DarkScent9** [Truthkey/KH2FMRandomizer#7]
I have yet to get a run past Roxas world because Roxas can't beat 90% of the bosses.

Some notable ones:

Stormrider at Seifer 1 (the one where you have to land a combo on the boss to continue) (from a previous version)
Lexeaus AS at Axel 1 (Can't RC to kill him? I had no scan, therefore don't know if finisher after his power up deal damage.)
Data Xemnas at Axel 1 (Just can't. Not enough options to fight him, and RC will probably softlock, if Roxas could use it.)
Data Xaldin at Axel 2 (No Guard (because of dual swords) and no RC? Is there even a way to beat him?) (From a previous version)

In general, if the Boss has a RC, and it is not one of Roxas Bosses, there is a good chance Roxas can't use it. If it is necessary to beat the boss, then Roxas can't fight it.

On the same note, Twilight Thorns should stay with Roxas, as Sora can't use Twilight thorns big RC and will T-Stance.

**Comment by Flowleyd** [comment]
also Data Xigbar at Axel 1 (possibly at any other Roxas fight aswell) instant kills you before you are even able to move.

**Comment by Truthkey** [comment]
I will soon add the option to not randomize the prologue. Sometimes the bosses are just too hard to beat.
