### ISSUE TITLE
Bonus Reward Seed 1BE1DFCB crashes on twilight thorn death.

### ISSUE THREAD

**Issue by DarkScent9** [Truthkey/KH2FMRandomizer#8]
Title. 

[SpoilerLog_BonusRewards.txt](https://github.com/Truthkey/KH2FMRandomizer/files/4239828/SpoilerLog_BonusRewards.txt)

**Comment by Truthkey** [comment]
Thanks. If you download the latest version, there shouldn't be crashes anymore related to Bonus Rewards!
