### ISSUE TITLE
Are certain Org Datas missing?

### ISSUE THREAD

**Issue by DarkScent9** [Truthkey/KH2FMRandomizer#9]
Because in the GUI, it's impossible to blacklist them.

Are they always blacklisted and, if yes, why if their AS are not? 

Specifically,

Data Vexen
Data Marluxia
Data Laxeaus
Data Roxas 
Data Larxene
Data Zexion

**Comment by Truthkey** [comment]
I'm pretty positive they aren't blacklisted internally. They should randomize like any other fight.
In fact, you should be able to check the randomization log to see what the AS bosses should have been replaced with.
